// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RangeController from "./range_controller"
application.register("range", RangeController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)

import SwypeIndexController from "./swype_index_controller"
application.register("swype-index", SwypeIndexController)
